### ISSUE TITLE
About section not loading on portfolio (possible API error)

### ISSUE THREAD

**Issue by pchaudhary12** [mayankagarwal09/dev-portfolio#24]
I am trying to create my Portfolio, but I was running through an error, the "about" section is not loading on the localhost,
it is giving this error: 
"react-dom.development.js:67 
 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: RevealBase
" 
All the other parts of the website is working, I went through the React help forums but cannot really solve as React is not my expertise.
Please let me know how to resolve this 

Thank You
Pruthvi
![Screenshot 2024-06-02 200515](https://github.com/mayankagarwal09/dev-portfolio/assets/132619754/01c23025-c168-4303-a0b8-801a00663a3e)

**Comment by amiii123malviya** [comment]
is this issue still active??

**Comment by pchaudhary12** [comment]
This is solved, it was really simple, the issue it was causing was that when you copy paste a commend or text from other document to the JSON file, it changes the JSON formatting and causes the error. Closing the issue
