### ISSUE TITLE
Not clickable

### ISSUE THREAD

**Issue by alwayswelcom** [mayankagarwal09/dev-portfolio#5]
Once launch your project on my local, there is some unexpected iframe on there and that is existed on top.
So I could not select any things and wanna delete it.
How to?

**Comment by Jiaying330** [comment]
I came across the same issue, and my solution is to go to src/components/projects/ProjectCards.jsx line 97 and change PropTypes.object to PropTypes.objects() and this works for me

**Comment by mayankagarwal09** [comment]
fixed in PR #6
